// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var Assets = Assets || {};

/**
 * @const
 * @namespace
 */
Assets.Code = Assets.Code || {};

/**
 * @const
 * @namespace
 */
Assets.Code.Remote = Assets.Code.Remote || {};

/**
 * @const
 * @namespace
 */
Assets.Code.Remote.Flat = Assets.Code.Remote.Flat || {};

/**
 * @constructor
 */
Assets.Code.Remote.Flat.ErrorMessage = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Assets.Code.Remote.Flat.ErrorMessage}
 */
Assets.Code.Remote.Flat.ErrorMessage.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Assets.Code.Remote.Flat.ErrorMessage=} obj
 * @returns {Assets.Code.Remote.Flat.ErrorMessage}
 */
Assets.Code.Remote.Flat.ErrorMessage.getRootAsErrorMessage = function(bb, obj) {
  return (obj || new Assets.Code.Remote.Flat.ErrorMessage).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {boolean}
 */
Assets.Code.Remote.Flat.ErrorMessage.bufferHasIdentifier = function(bb) {
  return bb.__has_identifier('ERRM');
};

/**
 * @returns {number}
 */
Assets.Code.Remote.Flat.ErrorMessage.prototype.errorCode = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Assets.Code.Remote.Flat.ErrorMessage.prototype.message = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Assets.Code.Remote.Flat.ErrorMessage.startErrorMessage = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} errorCode
 */
Assets.Code.Remote.Flat.ErrorMessage.addErrorCode = function(builder, errorCode) {
  builder.addFieldInt32(0, errorCode, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} messageOffset
 */
Assets.Code.Remote.Flat.ErrorMessage.addMessage = function(builder, messageOffset) {
  builder.addFieldOffset(1, messageOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Assets.Code.Remote.Flat.ErrorMessage.endErrorMessage = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
Assets.Code.Remote.Flat.ErrorMessage.finishErrorMessageBuffer = function(builder, offset) {
  builder.finish(offset, 'ERRM');
};

// Exports for Node.js and RequireJS
this.Assets = Assets;
