// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var Assets = Assets || {};

/**
 * @const
 * @namespace
 */
Assets.Code = Assets.Code || {};

/**
 * @const
 * @namespace
 */
Assets.Code.Remote = Assets.Code.Remote || {};

/**
 * @enum
 */
Assets.Code.Remote.Data = {
  NONE: 0,
  PlayerData: 1,
  ShootData: 2
};

/**
 * @constructor
 */
Assets.Code.Remote.Vec3 = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Assets.Code.Remote.Vec3}
 */
Assets.Code.Remote.Vec3.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {number}
 */
Assets.Code.Remote.Vec3.prototype.x = function() {
  return this.bb.readFloat32(this.bb_pos);
};

/**
 * @returns {number}
 */
Assets.Code.Remote.Vec3.prototype.y = function() {
  return this.bb.readFloat32(this.bb_pos + 4);
};

/**
 * @returns {number}
 */
Assets.Code.Remote.Vec3.prototype.z = function() {
  return this.bb.readFloat32(this.bb_pos + 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} x
 * @param {number} y
 * @param {number} z
 * @returns {flatbuffers.Offset}
 */
Assets.Code.Remote.Vec3.createVec3 = function(builder, x, y, z) {
  builder.prep(4, 12);
  builder.writeFloat32(z);
  builder.writeFloat32(y);
  builder.writeFloat32(x);
  return builder.offset();
};

/**
 * @constructor
 */
Assets.Code.Remote.PlayerData = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Assets.Code.Remote.PlayerData}
 */
Assets.Code.Remote.PlayerData.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Assets.Code.Remote.PlayerData=} obj
 * @returns {Assets.Code.Remote.PlayerData}
 */
Assets.Code.Remote.PlayerData.getRootAsPlayerData = function(bb, obj) {
  return (obj || new Assets.Code.Remote.PlayerData).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {Assets.Code.Remote.Vec3=} obj
 * @returns {Assets.Code.Remote.Vec3}
 */
Assets.Code.Remote.PlayerData.prototype.position = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new Assets.Code.Remote.Vec3).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {Assets.Code.Remote.Vec3=} obj
 * @returns {Assets.Code.Remote.Vec3}
 */
Assets.Code.Remote.PlayerData.prototype.rotation = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new Assets.Code.Remote.Vec3).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Assets.Code.Remote.PlayerData.startPlayerData = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} positionOffset
 */
Assets.Code.Remote.PlayerData.addPosition = function(builder, positionOffset) {
  builder.addFieldStruct(0, positionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} rotationOffset
 */
Assets.Code.Remote.PlayerData.addRotation = function(builder, rotationOffset) {
  builder.addFieldStruct(1, rotationOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Assets.Code.Remote.PlayerData.endPlayerData = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
Assets.Code.Remote.ShootData = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Assets.Code.Remote.ShootData}
 */
Assets.Code.Remote.ShootData.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Assets.Code.Remote.ShootData=} obj
 * @returns {Assets.Code.Remote.ShootData}
 */
Assets.Code.Remote.ShootData.getRootAsShootData = function(bb, obj) {
  return (obj || new Assets.Code.Remote.ShootData).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {Assets.Code.Remote.Vec3=} obj
 * @returns {Assets.Code.Remote.Vec3}
 */
Assets.Code.Remote.ShootData.prototype.position = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new Assets.Code.Remote.Vec3).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {Assets.Code.Remote.Vec3=} obj
 * @returns {Assets.Code.Remote.Vec3}
 */
Assets.Code.Remote.ShootData.prototype.direction = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new Assets.Code.Remote.Vec3).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @returns {boolean}
 */
Assets.Code.Remote.ShootData.prototype.alternate = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Assets.Code.Remote.ShootData.startShootData = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} positionOffset
 */
Assets.Code.Remote.ShootData.addPosition = function(builder, positionOffset) {
  builder.addFieldStruct(0, positionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} directionOffset
 */
Assets.Code.Remote.ShootData.addDirection = function(builder, directionOffset) {
  builder.addFieldStruct(1, directionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} alternate
 */
Assets.Code.Remote.ShootData.addAlternate = function(builder, alternate) {
  builder.addFieldInt8(2, +alternate, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Assets.Code.Remote.ShootData.endShootData = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
Assets.Code.Remote.GameData = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Assets.Code.Remote.GameData}
 */
Assets.Code.Remote.GameData.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Assets.Code.Remote.GameData=} obj
 * @returns {Assets.Code.Remote.GameData}
 */
Assets.Code.Remote.GameData.getRootAsGameData = function(bb, obj) {
  return (obj || new Assets.Code.Remote.GameData).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {boolean}
 */
Assets.Code.Remote.GameData.bufferHasIdentifier = function(bb) {
  return bb.__has_identifier('GAME');
};

/**
 * @returns {Assets.Code.Remote.Data}
 */
Assets.Code.Remote.GameData.prototype.dataType = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {Assets.Code.Remote.Data} */ (this.bb.readUint8(this.bb_pos + offset)) : Assets.Code.Remote.Data.NONE;
};

/**
 * @param {flatbuffers.Table} obj
 * @returns {?flatbuffers.Table}
 */
Assets.Code.Remote.GameData.prototype.data = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Assets.Code.Remote.GameData.startGameData = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Assets.Code.Remote.Data} dataType
 */
Assets.Code.Remote.GameData.addDataType = function(builder, dataType) {
  builder.addFieldInt8(0, dataType, Assets.Code.Remote.Data.NONE);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} dataOffset
 */
Assets.Code.Remote.GameData.addData = function(builder, dataOffset) {
  builder.addFieldOffset(1, dataOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Assets.Code.Remote.GameData.endGameData = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
Assets.Code.Remote.GameData.finishGameDataBuffer = function(builder, offset) {
  builder.finish(offset, 'GAME');
};

// Exports for Node.js and RequireJS
this.Assets = Assets;
